# These are supported funding model platforms
custom: ['https://www.paypal.me/makespacemadrid','https://www.gofundme.com/manage/apoya-el-futuro-de-makespace-madrid', 'https://www.teaming.net/makespacemadrid-grupo']
